function skillsMember() {
  let skills = [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Node",
    "Express",
    "MongoDB",
    "Python",
    "Django",
    "Flask",
    "Ruby",
    "Rails",
    "PostgreSQL",
    "MySQL",
    "SQL",
    "Java",
    "C#",
    "C++",
    "C",
    "PHP",
    "Laravel",
    "Vue",
    "Angular",
    "Swift",
    "Kotlin",
    "Android",
    "iOS",
    "Git",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Heroku",
    "Netlify",
    "Vercel",
    "DigitalOcean",
    "Firebase",
    "Auth0",
    "OAuth",
    "JWT",
    "REST",
    "GraphQL",
    "API",
    "CI/CD",
    "TDD",
    "BDD",
    "Agile",
    "Scrum",
    "Kanban",
    "Jira",
    "Confluence",
    "Trello",
    "Slack",
    "Zoom",
    "Discord",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Photoshop",
    "Illustrator",
    "InDesign",
    "Premiere",
    "After Effects",
    "Blender",
    "Unity",
    "Unreal Engine",
    "3ds Max",
    "Maya",
    "ZBrush",
    "AutoCAD",
    "SolidWorks",
    "Fusion 360",
    "SketchUp",
    "Revit",
    "Rhino",
    "Grasshopper",
    "Arduino",
    "Raspberry Pi",
    "IoT",
    "VR",
    "AR",
    "AI",
    "ML",
    "DL",
    "NLP",
    "CV",
    "Blockchain",
    "Cryptocurrency",
    "DeFi",
    "Web3",
    "Smart Contract",
    "Solidity",
    "Rust",
    "Ethereum",
    "Bitcoin",
    "Polkadot",
    "Cardano",
    "Chainlink",
    "Filecoin",
    "IPFS",
    "NFT",
    "DAO",
    "DAOstack",
    "Aragon",
    "Gnosis",
    "Compound",
    "Aave",
    "Uniswap",

    // Add more skills here
  ];};